
[project]
name = "zyk"
version = "0.2.46"
description = "Simple LM api wrappers for production"
readme = "README.md"
authors = [{ name = "Josh Purtell", email = "jmvpurtell@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["zyk"]
dependencies = [
    "openai",
    "pydantic",
    "diskcache",
    "backoff>=2.2.1",
    "anthropic>=0.34.2",
    "google>=3.0.0",
    "google-generativeai>=0.8.1",
    "together>=1.2.12",
    "langfuse>=2.56.1",
    "synth-sdk==0.2.121",
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/JoshuaPurtell/jazyk"

[tool.hatch.build.targets.wheel]
packages = ["zyk"]

[tool.hatch.upload.pypi]
repository = "https://upload.pypi.org/legacy/"
username = "__token__"
password = "${PYPI_API_TOKEN}"
