
[project]
name = "synth-ai"
version = "0.0.0.dev1"
description = "Software for aiding the best and multiplying the will."
readme = "README.md"
authors = [{ name = "Josh Purtell", email = "josh@usesynth.ai" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["synth-ai"]
dependencies = [
    "openai",
    "pydantic",
    "diskcache",
    "backoff>=2.2.1",
    "anthropic>=0.34.2",
    "google>=3.0.0",
    "google-generativeai>=0.8.1",
    "together>=1.2.12",
    "langfuse>=2.56.1",
    "synth-sdk==0.3.0",
    "datasets>=3.2.0",
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/synth-laboratories/synth-ai"

[tool.hatch.build.targets.wheel]
packages = ["synht-ai"]

[tool.hatch.upload.pypi]
repository = "https://upload.pypi.org/legacy/"
username = "__token__"
password = "${PYPI_API_TOKEN}"
